# On the cluster, these are the calls generated by R CMD SHLIB on .c
# and .cpp files:
#
# gcc -I"$R_HOME/include" -DNDEBUG -I/usr/local/include \
#    -fpic  -g -O2  -c hello.c -o hello.o
# gcc -shared -L$R_HOME/lib -L$R_HOME/lib -Wl,-rpath,$R_HOME/lib \
#    -o hello.so hello.o -L$R_HOME/lib -lR
#
# g++ -std=gnu++11 -I"$R_HOME/include" -DNDEBUG -I/usr/local/include \
#    -fpic  -g -O2  -c hello.cpp -o hello.o
# g++ -std=gnu++11 -shared -L$R_HOME/lib -Wl,-rpath,$R_HOME/lib \
#    -o hello.so hello.o -L$R_HOME/lib -lR

# We can adapt them for now, directly:
module load Core/gcc/8.4.0 gcc/8.4.0/r/4.0.2
module load cuda/10.1

R_HOME=$(Rscript -e 'cat(Sys.getenv("R_HOME"))')
nvcc -O3 -G -I$R_HOME/include -Xcompiler -fpic -x cu -c cufft.cu -o cufft.o
nvcc -G -L$R_HOME/lib -lcufft -lR --shared -o cufft.so cufft.o

nvcc -O3 -G -I$R_HOME/include -Xcompiler -fpic -x cu -c add.cu -o add.o
nvcc -G -L$R_HOME/lib -ladd -lR --shared -o add.so add.o
