# Generated by cpp11: do not edit by hand

prototype <- function(alpha, beta, gamma, I0, n_particles, n_steps, n_record, seed) {
  .Call("_prototype_prototype", alpha, beta, gamma, I0, n_particles, n_steps, n_record, seed)
}

dust_sireinfect_alloc <- function(r_data, step, n_particles, n_threads, seed) {
  .Call("_prototype_dust_sireinfect_alloc", r_data, step, n_particles, n_threads, seed)
}

dust_sireinfect_run <- function(ptr, step_end) {
  .Call("_prototype_dust_sireinfect_run", ptr, step_end)
}

dust_sireinfect_set_index <- function(ptr, r_index) {
  .Call("_prototype_dust_sireinfect_set_index", ptr, r_index)
}

dust_sireinfect_set_state <- function(ptr, r_state, r_step) {
  .Call("_prototype_dust_sireinfect_set_state", ptr, r_state, r_step)
}

dust_sireinfect_reset <- function(ptr, r_data, step) {
  .Call("_prototype_dust_sireinfect_reset", ptr, r_data, step)
}

dust_sireinfect_state <- function(ptr, r_index) {
  .Call("_prototype_dust_sireinfect_state", ptr, r_index)
}

dust_sireinfect_step <- function(ptr) {
  .Call("_prototype_dust_sireinfect_step", ptr)
}

dust_sireinfect_reorder <- function(ptr, r_index) {
  invisible(.Call("_prototype_dust_sireinfect_reorder", ptr, r_index))
}

dust_sirs_alloc <- function(r_data, step, n_particles, n_threads, seed) {
  .Call("_prototype_dust_sirs_alloc", r_data, step, n_particles, n_threads, seed)
}

dust_sirs_run <- function(ptr, step_end) {
  .Call("_prototype_dust_sirs_run", ptr, step_end)
}

dust_sirs_set_index <- function(ptr, r_index) {
  .Call("_prototype_dust_sirs_set_index", ptr, r_index)
}

dust_sirs_set_state <- function(ptr, r_state, r_step) {
  .Call("_prototype_dust_sirs_set_state", ptr, r_state, r_step)
}

dust_sirs_reset <- function(ptr, r_data, step) {
  .Call("_prototype_dust_sirs_reset", ptr, r_data, step)
}

dust_sirs_state <- function(ptr, r_index) {
  .Call("_prototype_dust_sirs_state", ptr, r_index)
}

dust_sirs_step <- function(ptr) {
  .Call("_prototype_dust_sirs_step", ptr)
}

dust_sirs_reorder <- function(ptr, r_index) {
  invisible(.Call("_prototype_dust_sirs_reorder", ptr, r_index))
}
